<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SmoothAiStockAnalysis.TestFramework.Aspire</RootNamespace>
    <IsAspireHost>true</IsAspireHost>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
