<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmoothAiStockAnalysis.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmoothAiStockAnalysis.Application\SmoothAiStockAnalysis.Application.csproj" />
    <ProjectReference Include="..\SmoothAiStockAnalysis.Domain\SmoothAiStockAnalysis.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmoothAiStockAnalysis.Infrastructure.UnitTest" />
    <InternalsVisibleTo Include="SmoothAiStockAnalysis.Infrastructure.ComponentTest" />
  </ItemGroup>

</Project>
