// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmoothAiStockAnalysis.Infrastructure.Persistence;

#nullable disable

namespace SmoothAiStockAnalysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmoothAiStockAnalysisDbContext))]
    [Migration("20260724113407_SnakeCaseNamingConvention")]
    partial class SnakeCaseNamingConvention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SmoothAiStockAnalysis.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<Guid>("UniqueIdentifier")
                        .HasColumnType("TEXT")
                        .HasColumnName("unique_identifier");

                    b.HasKey("Id")
                        .HasName("pk_user_record");

                    b.HasIndex("UniqueIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_user_record_unique_identifier");

                    b.ToTable("user_record", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
