<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SmoothAiStockAnalysis.Host</RootNamespace>
    <UserSecretsId>smooth-ai-stockanalysis-host</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmoothAiStockAnalysis.Application\SmoothAiStockAnalysis.Application.csproj" />
    <ProjectReference Include="..\SmoothAiStockAnalysis.Domain\SmoothAiStockAnalysis.Domain.csproj" />
    <ProjectReference Include="..\SmoothAiStockAnalysis.Infrastructure\SmoothAiStockAnalysis.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmoothAiStockAnalysis.Host.UnitTest" />
    <InternalsVisibleTo Include="SmoothAiStockAnalysis.Host.IntegrationTest" />
  </ItemGroup>

</Project>
